swagger: "2.0"
info:
  title: "OneCloud API"
  version: "1.0"
  termsOfService: ""
  contact:
    email: zhouyousong@yunion.cn
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

host: "10.168.222.136:8889"
basePath: "/"

schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json

tags:
  - name: loadbalancers
  - name: loadbalancerlisteners
  - name: loadbalancerbackendgroups
  - name: loadbalancerbackends

paths:
  /loadbalancers:
    get:
      summary: 按指定条件列出loadbalancer实例
      parameters:
      - name: address
        in: query
        type: string
        description: 指定virtual ip地址
      responses:
        200:
          description: 实例列表信息
          schema:
            $ref: '#/definitions/LoadbalancerListResponse'
      tags:
        - loadbalancers
    post:
      summary: 创建loadbalancer实例
      responses:
        200:
          description: 新创建的实例信息
          schema:
            $ref: '#/definitions/LoadbalancerResponse'
      tags:
        - loadbalancers
  /loadbalancers/{loadbalancerId}:
    parameters: 
    - name: loadbalancerId
      type: string
      in: path
      required: true
    get:
      summary: 获取指定loadbalancer实例信息
      responses:
        200:
          description: 实例信息
          schema:
            $ref: '#/definitions/LoadbalancerResponse'
      tags:
        - loadbalancers
    delete:
      summary: 删除指定loadbalancer实例
      responses:
        200:
          description: 被删除实例的信息
          schema:
            $ref: '#/definitions/LoadbalancerResponse'
      tags:
        - loadbalancers

  /loadbalancerlisteners:
    get:
      summary: 按指定条件列出loadbalancer监听实例
      parameters:
      - name: loadbalancer
        in: query
        type: string
        description: 指定loadbalaner实例uuid
      - name: listener_type
        in: query
        type: string
        enum:
          - tcp
        description: 指定loadbalaner监听协议
      - name: listener_port
        in: query
        type: integer
        description: 指定loadbalaner监听端口
      responses:
        200:
          description: 监听实例列表信息
          schema:
            $ref: '#/definitions/LoadbalancerListenerListResponse'
      tags:
        - loadbalancerlisteners
    post:
      summary: 创建loadbalancer监听实例
      parameters:
      - name: loadbalancerlistener
        in: body
        required: true
        schema:
          $ref: '#/definitions/LoadbalancerListenerCreateRequest'
      responses:
        200:
          description: 新创建的实例信息
          schema:
            $ref: '#/definitions/LoadbalancerListenerResponse'
      tags:
        - loadbalancerlisteners
  /loadbalancerlisteners/{loadbalancerListenerId}:
    parameters: 
    - name: loadbalancerListenerId
      type: string
      in: path
      required: true
    get:
      summary: 获取指定loadbalancer监听实例信息
      responses:
        200:
          description: 实例信息
          schema:
            $ref: '#/definitions/LoadbalancerListenerResponse'
      tags:
        - loadbalancerlisteners
    delete:
      summary: 删除指定loadbalancer监听实例
      responses:
        200:
          description: 被删除实例的信息
          schema:
            $ref: '#/definitions/LoadbalancerListenerResponse'
      tags:
        - loadbalancerlisteners

  /loadbalancerbackendgroups:
    get:
      summary: 按指定条件列出loadbalancer后端服务器组
      parameters:
      - name: loadbalancer
        in: query
        type: string
        description: 指定loadbalaner实例uuid
      responses:
        200:
          description: 后端服务器组列表
          schema:
            $ref: '#/definitions/LoadbalancerBackendGroupListResponse'
      tags:
        - loadbalancerbackendgroups
    post:
      summary: 创建loadbalancer后端服务器组
      parameters:
      - name: loadbalancer
        in: body
        schema: { type: string }
        required: true
        description: 指定loadbalaner实例uuid
      responses:
        200:
          description: 新创建的后端服务器组信息
          schema:
            $ref: '#/definitions/LoadbalancerBackendGroupResponse'
      tags:
        - loadbalancerbackendgroups
  /loadbalancerbackendgroups/{loadbalancerBackendGroupId}:
    parameters: 
    - name: loadbalancerBackendGroupId
      type: string
      in: path
      required: true
    get:
      summary: 获取指定loadbalancer后端服务器组信息
      responses:
        200:
          description: 实例信息
          schema:
            $ref: '#/definitions/LoadbalancerBackendGroupResponse'
      tags:
        - loadbalancerbackendgroups
    delete:
      summary: 删除指定loadbalancer后端服务器组实例
      responses:
        200:
          description: 被删除实例的信息
          schema:
            $ref: '#/definitions/LoadbalancerBackendGroupResponse'
      tags:
        - loadbalancerbackendgroups

  /loadbalancerbackends:
    get:
      summary: 按指定条件列出loadbalancer后端服务器
      parameters:
      - name: backend_group
        in: query
        type: string
        description: 指定loadbalaner后端服务器组uuid
      - name: address
        in: query
        type: string
        description: 指定real ip
      - name: port
        in: query
        type: integer
        description: 指定real port
      responses:
        200:
          description: 后端服务器组列表
          schema:
            $ref: '#/definitions/LoadbalancerBackendListResponse'
      tags:
        - loadbalancerbackends
    post:
      summary: 创建loadbalancer后端服务器
      parameters:
      - name: loadbalancerbackend
        in: body
        schema:
          $ref: '#/definitions/LoadbalancerBackendCreateRequest'
      responses:
        200:
          description: 新创建的后端服务器组信息
          schema:
            $ref: '#/definitions/LoadbalancerBackendResponse'
      tags:
        - loadbalancerbackends
  /loadbalancerbackends/{loadbalancerBackendId}:
    parameters: 
    - name: loadbalancerBackendId
      type: string
      in: path
      required: true
    get:
      summary: 获取指定loadbalancer后端服务器信息
      responses:
        200:
          description: 实例信息
          schema:
            $ref: '#/definitions/LoadbalancerBackendResponse'
      tags:
        - loadbalancerbackends
    delete:
      summary: 删除指定loadbalancer后端服务器
      responses:
        200:
          description: 被删除后端服务器的信息
          schema:
            $ref: '#/definitions/LoadbalancerBackendResponse'
      tags:
        - loadbalancerbackends

definitions:
  Loadbalancer:
    type: object
    description: Loadbalancer实例
    properties:
      id:
        type: string
        description: 实例uuid
        readOnly: true
      address:
        type: string
        description: 实例IP地址，即virtual ip
        readOnly: true

  LoadbalancerListener:
    type: object
    description: Loadbalancer监听实例
    properties:
      id:
        type: string
        description: 实例uuid
        readOnly: true
      loadbalancer_id:
        type: string
        description: 所属的loadbalancer的uuid
        readOnly: true
      listener_type:
        type: string
        description: 监听协议类型
        enum:
          - tcp
        readOnly: true
      listener_port:
        type: integer
        description: 监听端口，即virtual port
        readOnly: true
      scheduler:
        type: string
        description: 调度算法
        readOnly: true
        
  LoadbalancerBackendGroup:
    type: object
    description: Loadbalancer后端服务器组实例
    properties:
      id:
        type: string
        description: 实例uuid
        readOnly: true
      loadbalancer_id:
        type: string
        description: 所属的loadbalancer的uuid
        readOnly: true

  LoadbalancerBackend:
    type: object
    description: Loadbalancer后端实例
    properties:
      id:
        type: string
        description: 实例uuid
        readOnly: true
      backend_group_id:
        type: string
        description: 所属的loadbalancer后端服务器组uuid
        readOnly: true
      backend_type:
        type: string
        description: 后端服务器类型
        readOnly: true
        enum:
          - guest
          - host
          - ip
      address:
        type: string
        description: 后端IP地址，即real ip
        readOnly: true
      port:
        type: string
        description: 后端端口，即real port
        readOnly: true
      weight:
        type: integer
        description: 后端权重

  LoadbalancerListResponse:
    type: object
    properties:
      loadbalancers:
        type: array
        items:
          $ref: '#/definitions/Loadbalancer'
  LoadbalancerResponse:
    type: object
    properties:
      loadbalancer:
        type: object
        $ref: '#/definitions/Loadbalancer'

  LoadbalancerListenerCreateRequest:
    type: object
    properties:
      loadbalancerlistener:
        type: object
        required:
          - loadbalancer
          - listener_type
          - listener_port
          - scheduler
        properties:
          loadbalancer:
            type: string
            description: 指定loadbalaner实例uuid
          listener_type:
            type: string
            enum:
              - tcp
            description: 指定loadbalaner监听协议
          listener_port:
            type: integer
            description: 指定loadbalaner监听端口
          scheduler:
            type: string
            description: 指定监听的调度算法
            enum:
              - rr
              - wrr
              - wlc
              - sch
              - tch
          backend_group:
            type: string
            description: 指定后端服务器组uuid
  LoadbalancerListenerListResponse:
    type: object
    properties:
      loadbalancerlisteners:
        type: array
        items:
          $ref: '#/definitions/LoadbalancerListener'
  LoadbalancerListenerResponse:
    type: object
    properties:
      loadbalancerlistener:
        type: object
        $ref: '#/definitions/LoadbalancerListener'
          
  LoadbalancerBackendGroupListResponse:
    type: object
    properties:
      loadbalancerbackendgroups:
        type: array
        items:
          $ref: '#/definitions/LoadbalancerBackendGroup'
  LoadbalancerBackendGroupResponse:
    type: object
    properties:
      loadbalancerbackendgroup:
        type: object
        $ref: '#/definitions/LoadbalancerBackendGroup'

  LoadbalancerBackendCreateRequest:
    type: object
    properties:
      loadbalancerbackend:
        type: object
        required:
          - backend_group
          - backend_type
          - backend
          - port
          - weight
        properties:
          backend_group:
            type: string
            description: 指定loadbalaner后端服务器组uuid
          backend_type:
            type: string
            enum:
              - guest
              - host
              - ip
            description: 指定后端服务器的类型。仅管理员能够指定host, ip为后端服务器
          backend:
            type: string
            description: 后端服务器的标识信息

              当backend_type为guest时，该字段的值应当是服务器的uuid

              当backend_type为host时，该字段的值应为宿主机的uuid

              当backend_type为ip时，该字段的值应为有效的IP地址
          port:
            type: integer
            description: 后端服务器的端口
          weight:
            type: integer
            description: 后端服务器的权重
  LoadbalancerBackendListResponse:
    type: object
    properties:
      loadbalancerbackends:
        type: array
        items:
          $ref: '#/definitions/LoadbalancerBackend'
  LoadbalancerBackendResponse:
    type: object
    properties:
      loadbalancerbackend:
        type: object
        $ref: '#/definitions/LoadbalancerBackend'
